name: Terraform Deploy

on:
  push: # Dispara automaticamente o pipeline quando há commits no branch `main`
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest # Define o ambiente de execução (máquina Linux padrão do GitHub Actions)

    steps:
      # 1. Fazer o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2
        # Baixa o código do repositório no ambiente de execução do GitHub Actions

      # 2. Configurar as credenciais da AWS para autenticação
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Chave de acesso configurada nos segredos do repositório
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Chave secreta configurada nos segredos
          aws-region: ${{ secrets.AWS_REGION }} # Região configurada nos segredos (ex.: us-east-1)

      # 3. Configurar o Terraform no ambiente
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        # Instala o Terraform na versão mais recente no ambiente de execução

      # 4. Inicializar o Terraform no diretório especificado
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      # 5. Validar a configuração Terraform
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra
        # Verifica se a sintaxe e a configuração do código Terraform estão corretas

      # 6. Atualizar o estado local do Terraform com os recursos reais da AWS
      - name: Terraform Refresh
        run: terraform refresh -input=false
        working-directory: ./infra
        # Atualiza o estado Terraform com a infraestrutura real, garantindo sincronização

      # 7. Aplicar as mudanças no Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra
        # Aplica as mudanças definidas no código Terraform automaticamente (sem necessidade de confirmação manual)
